import{a as y,S as b,i as n}from"./assets/vendor-BkC4bTqC.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();async function p(o,r){return(await y.get("https://pixabay.com/api/",{params:{key:"55050395-20e5244c38068275f8aacdcf3",q:o,page:r,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const L=new b(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}),c={container:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadmoreBtn:document.querySelector(".loadmore-btn")};function m(o){const r=o.map(t=>`
    <li>
      <a href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes</b><span>${t.likes}</span></p>
        <p><b>Views</b><span>${t.views}</span></p>
        <p><b>Comments</b><span>${t.comments}</span></p>
        <p><b>Downloads</b><span>${t.downloads}</span></p>
      </div>
    </li>
  `).join("");c.container.insertAdjacentHTML("beforeend",r),L.refresh()}function w(){c.container.innerHTML=""}function f(){c.loader.classList.remove("hidden")}function h(){c.loader.classList.add("hidden")}function g(){c.loadmoreBtn.classList.remove("hidden")}function l(){c.loadmoreBtn.classList.add("hidden")}const v=document.querySelector(".form"),S=document.querySelector(".loadmore-btn");let i,u;v.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(!r){n.error({title:"Error",message:"Please enter a search term!"});return}u=r,i=1,w(),l(),f();try{const t=await p(u,i),a=t.hits;if(a.length===0){n.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:4e3});return}m(a),Math.ceil(t.totalHits/15)<=i?(l(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):g(),o.target.reset()}catch(t){console.error(t),n.error({title:"Error",message:"Something went wrong. Please try again!",position:"topRight",timeout:4e3})}finally{h()}});S.addEventListener("click",async()=>{i+=1,l(),f();try{const o=await p(u,i),r=o.hits;m(r),Math.ceil(o.totalHits/15)<=i?(l(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):g();const e=document.querySelector(".gallery li").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}catch(o){console.error(o),n.error({title:"Error",message:"Something went wrong. Please try again!",position:"topRight",timeout:4e3})}finally{h()}});
//# sourceMappingURL=index.js.map
